// The report nameplates (industry/brand/nameplates/, made by scripts/nameplates.ts from the pack's
// subject word). The two paths are read out of the svg and drawn inline. They used to be a cross-document
// reference — `<use href="/geohot/assets/daily-….svg#accent">` — which costs one more request per colour
// before the masthead can paint, and WebKit has never resolved those reliably (docs/known-issues.md).
// This nameplate is the daily's LCP element, so the four svgs (19 kB of path data, about 5 kB gzipped)
// now travel in the report route's own chunk instead. The svg stays the single source: the paths are cut
// from it at build time, so nothing here has to be regenerated by hand.
import daily from "@aihot/industry/brand/nameplates/daily.svg?raw";
import weekly from "@aihot/industry/brand/nameplates/weekly.svg?raw";
import monthly from "@aihot/industry/brand/nameplates/monthly.svg?raw";
import archive from "@aihot/industry/brand/nameplates/archive.svg?raw";
import viewBoxes from "@aihot/industry/brand/nameplates/index.json";
import { nameplatePath } from "./nameplate-paths";

const NAMEPLATES = {
  daily: { accent: nameplatePath(daily, "accent"), ink: nameplatePath(daily, "ink"), viewBox: viewBoxes.daily },
  weekly: { accent: nameplatePath(weekly, "accent"), ink: nameplatePath(weekly, "ink"), viewBox: viewBoxes.weekly },
  monthly: { accent: nameplatePath(monthly, "accent"), ink: nameplatePath(monthly, "ink"), viewBox: viewBoxes.monthly },
  archive: { accent: nameplatePath(archive, "accent"), ink: nameplatePath(archive, "ink"), viewBox: viewBoxes.archive },
} as const;

export function Nameplate({ which, className = "" }: { which: keyof typeof NAMEPLATES; className?: string }) {
  const n = NAMEPLATES[which];
  return (
    <svg viewBox={n.viewBox} className={className} aria-hidden="true" focusable="false">
      <path d={n.accent} className="fill-accent" />
      <path d={n.ink} className="fill-ink" />
    </svg>
  );
}
